/*
* Unique Generalized Abbreviations (hard)
* Given a word, write a function to generate all of its unique generalized abbreviations.
* Generalized abbreviation of a word can be generated by replacing each substring of the
* word by the count of characters in the substring. Take the example of “ab” which has
* four substrings: “”, “a”, “b”, and “ab”. After replacing these substrings in the actual
* word by the count of characters we get all the generalized abbreviations: “ab”, “1b”, “a1”, and “2”.
* */

import java.util.*;

class AbbreviatedWord {
    StringBuilder str;
    int start;
    int count;

    public AbbreviatedWord(StringBuilder str, int start, int count) {
        this.str = str;
        this.start = start;
        this.count = count;
    }
}

class GeneralizedAbbreviation {

    public static List<String> generateGeneralizedAbbreviation(String word) {
        List<String> res = new ArrayList<String>();
        Queue<AbbreviatedWord> queue = new LinkedList<>();
        queue.add(new AbbreviatedWord(new StringBuilder(), 0, 0));
        while (!queue.isEmpty()) {
            AbbreviatedWord temp = queue.poll();
            if( temp.start == word.length()){
                if( temp.count != 0)
                    temp.str.append(temp.count);
                res.add(temp.str.toString());
            }else{
                queue.add(new AbbreviatedWord(
                        new StringBuilder(temp.str),
                        temp.start+1,
                        temp.count+1));

                if( temp.count != 0)
                    temp.str.append(temp.count);

                queue.add(new AbbreviatedWord(
                        new StringBuilder(temp.str).append(word.charAt(temp.start)),
                        temp.start+1,
                        0));
            }

        }
        return res;
    }

    public static void main(String[] args) {
        List<String> result = GeneralizedAbbreviation.generateGeneralizedAbbreviation("BAT");
        System.out.println("Generalized abbreviation are: " + result);

        result = GeneralizedAbbreviation.generateGeneralizedAbbreviation("code");
        System.out.println("Generalized abbreviation are: " + result);
    }
}
